import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import "./globals.css";
import RouteLayoutProvider from './provider/routLayoutProvider';
import Dashboard from './dashboard/page';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Spam Detector',
  description: 'Generated by App Developer',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RouteLayoutProvider>
          <div>
            <Dashboard></Dashboard>
          </div>
          <div>{children}</div>
        </RouteLayoutProvider>
      </body>
    </html>
  );
}
